[package]
name = "signer-backend"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.8"
ic-cdk = "0.17.1"
serde_bytes = "0.11.14"
serde = { version = "1.0.200", features = ["derive"] }
itertools = "0.12.1"
